/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'hours' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'bookingUrl' : string,
}
export interface ContactMessage {
  'id' : MessageId,
  'name' : string,
  'createdAt' : Timestamp,
  'preferredService' : string,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export type ImageId = bigint;
export type MessageId = bigint;
export interface PortfolioImage {
  'id' : ImageId,
  'title' : string,
  'createdAt' : Timestamp,
  'image' : ExternalBlob,
  'serviceTypeId' : ServiceTypeId,
}
export interface ServiceType {
  'id' : ServiceTypeId,
  'name' : string,
  'slug' : string,
  'description' : string,
}
export type ServiceTypeId = bigint;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, ServiceTypeId, ExternalBlob],
    PortfolioImage
  >,
  'addService' : ActorMethod<[string, string, string], ServiceType>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[ImageId], boolean>,
  'deleteService' : ActorMethod<[ServiceTypeId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getGalleryItem' : ActorMethod<[ImageId], [] | [PortfolioImage]>,
  'getService' : ActorMethod<[ServiceTypeId], [] | [ServiceType]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContacts' : ActorMethod<[], Array<ContactMessage>>,
  'listGalleryItems' : ActorMethod<[], Array<PortfolioImage>>,
  'listGalleryItemsByService' : ActorMethod<
    [ServiceTypeId],
    Array<PortfolioImage>
  >,
  'listServices' : ActorMethod<[], Array<ServiceType>>,
  'setContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactMessage
  >,
  'updateService' : ActorMethod<
    [ServiceTypeId, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];