/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceTypeId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const PortfolioImage = IDL.Record({
  'id' : ImageId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'image' : ExternalBlob,
  'serviceTypeId' : ServiceTypeId,
});
export const ServiceType = IDL.Record({
  'id' : ServiceTypeId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'Rescheduled' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TechId = IDL.Nat;
export const BookingView = IDL.Record({
  'id' : BookingId,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : IDL.Text,
  'customerPhone' : IDL.Text,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'confirmedDate' : IDL.Opt(IDL.Text),
  'confirmedTime' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'requestedDate' : IDL.Text,
  'requestedTime' : IDL.Text,
  'techId' : TechId,
  'adminNotes' : IDL.Opt(IDL.Text),
  'techName' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'bookingUrl' : IDL.Text,
});
export const NailTech = IDL.Record({
  'id' : TechId,
  'name' : IDL.Text,
  'town' : IDL.Text,
  'address' : IDL.Text,
  'specialties' : IDL.Vec(IDL.Text),
});
export const MessageId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : MessageId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'preferredService' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const RescheduleRequest = IDL.Record({
  'bookingId' : BookingId,
  'adminNotes' : IDL.Opt(IDL.Text),
  'newDate' : IDL.Text,
  'newTime' : IDL.Text,
});
export const CreateBookingRequest = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : IDL.Text,
  'customerPhone' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'requestedDate' : IDL.Text,
  'requestedTime' : IDL.Text,
  'techId' : TechId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, ServiceTypeId, ExternalBlob],
      [PortfolioImage],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ServiceType], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func(
      [BookingId, IDL.Opt(IDL.Text)],
      [IDL.Opt(BookingView)],
      [],
    ),
  'completeBooking' : IDL.Func(
      [BookingId, IDL.Opt(IDL.Text)],
      [IDL.Opt(BookingView)],
      [],
    ),
  'confirmBooking' : IDL.Func(
      [BookingId, IDL.Opt(IDL.Text)],
      [IDL.Opt(BookingView)],
      [],
    ),
  'deleteGalleryItem' : IDL.Func([ImageId], [IDL.Bool], []),
  'deleteService' : IDL.Func([ServiceTypeId], [IDL.Bool], []),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getGalleryItem' : IDL.Func([ImageId], [IDL.Opt(PortfolioImage)], ['query']),
  'getNailTech' : IDL.Func([TechId], [IDL.Opt(NailTech)], ['query']),
  'getService' : IDL.Func([ServiceTypeId], [IDL.Opt(ServiceType)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookings' : IDL.Func(
      [IDL.Opt(BookingStatus)],
      [IDL.Vec(BookingView)],
      ['query'],
    ),
  'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'listGalleryItems' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
  'listGalleryItemsByService' : IDL.Func(
      [ServiceTypeId],
      [IDL.Vec(PortfolioImage)],
      ['query'],
    ),
  'listNailTechs' : IDL.Func([], [IDL.Vec(NailTech)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
  'rescheduleBooking' : IDL.Func(
      [RescheduleRequest],
      [IDL.Opt(BookingView)],
      [],
    ),
  'setContactInfo' : IDL.Func([ContactInfo], [], []),
  'submitBooking' : IDL.Func([CreateBookingRequest], [BookingView], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'updateService' : IDL.Func(
      [ServiceTypeId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceTypeId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const PortfolioImage = IDL.Record({
    'id' : ImageId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'image' : ExternalBlob,
    'serviceTypeId' : ServiceTypeId,
  });
  const ServiceType = IDL.Record({
    'id' : ServiceTypeId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'Rescheduled' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TechId = IDL.Nat;
  const BookingView = IDL.Record({
    'id' : BookingId,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : IDL.Text,
    'customerPhone' : IDL.Text,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'confirmedDate' : IDL.Opt(IDL.Text),
    'confirmedTime' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'requestedDate' : IDL.Text,
    'requestedTime' : IDL.Text,
    'techId' : TechId,
    'adminNotes' : IDL.Opt(IDL.Text),
    'techName' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'bookingUrl' : IDL.Text,
  });
  const NailTech = IDL.Record({
    'id' : TechId,
    'name' : IDL.Text,
    'town' : IDL.Text,
    'address' : IDL.Text,
    'specialties' : IDL.Vec(IDL.Text),
  });
  const MessageId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : MessageId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'preferredService' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const RescheduleRequest = IDL.Record({
    'bookingId' : BookingId,
    'adminNotes' : IDL.Opt(IDL.Text),
    'newDate' : IDL.Text,
    'newTime' : IDL.Text,
  });
  const CreateBookingRequest = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : IDL.Text,
    'customerPhone' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'requestedDate' : IDL.Text,
    'requestedTime' : IDL.Text,
    'techId' : TechId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, ServiceTypeId, ExternalBlob],
        [PortfolioImage],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ServiceType], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func(
        [BookingId, IDL.Opt(IDL.Text)],
        [IDL.Opt(BookingView)],
        [],
      ),
    'completeBooking' : IDL.Func(
        [BookingId, IDL.Opt(IDL.Text)],
        [IDL.Opt(BookingView)],
        [],
      ),
    'confirmBooking' : IDL.Func(
        [BookingId, IDL.Opt(IDL.Text)],
        [IDL.Opt(BookingView)],
        [],
      ),
    'deleteGalleryItem' : IDL.Func([ImageId], [IDL.Bool], []),
    'deleteService' : IDL.Func([ServiceTypeId], [IDL.Bool], []),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getGalleryItem' : IDL.Func(
        [ImageId],
        [IDL.Opt(PortfolioImage)],
        ['query'],
      ),
    'getNailTech' : IDL.Func([TechId], [IDL.Opt(NailTech)], ['query']),
    'getService' : IDL.Func([ServiceTypeId], [IDL.Opt(ServiceType)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookings' : IDL.Func(
        [IDL.Opt(BookingStatus)],
        [IDL.Vec(BookingView)],
        ['query'],
      ),
    'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'listGalleryItems' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
    'listGalleryItemsByService' : IDL.Func(
        [ServiceTypeId],
        [IDL.Vec(PortfolioImage)],
        ['query'],
      ),
    'listNailTechs' : IDL.Func([], [IDL.Vec(NailTech)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
    'rescheduleBooking' : IDL.Func(
        [RescheduleRequest],
        [IDL.Opt(BookingView)],
        [],
      ),
    'setContactInfo' : IDL.Func([ContactInfo], [], []),
    'submitBooking' : IDL.Func([CreateBookingRequest], [BookingView], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'updateService' : IDL.Func(
        [ServiceTypeId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };