/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceTypeId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const PortfolioImage = IDL.Record({
  'id' : ImageId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'image' : ExternalBlob,
  'serviceTypeId' : ServiceTypeId,
});
export const ServiceType = IDL.Record({
  'id' : ServiceTypeId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'bookingUrl' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : MessageId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'preferredService' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, ServiceTypeId, ExternalBlob],
      [PortfolioImage],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ServiceType], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryItem' : IDL.Func([ImageId], [IDL.Bool], []),
  'deleteService' : IDL.Func([ServiceTypeId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getGalleryItem' : IDL.Func([ImageId], [IDL.Opt(PortfolioImage)], ['query']),
  'getService' : IDL.Func([ServiceTypeId], [IDL.Opt(ServiceType)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'listGalleryItems' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
  'listGalleryItemsByService' : IDL.Func(
      [ServiceTypeId],
      [IDL.Vec(PortfolioImage)],
      ['query'],
    ),
  'listServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
  'setContactInfo' : IDL.Func([ContactInfo], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'updateService' : IDL.Func(
      [ServiceTypeId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceTypeId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const PortfolioImage = IDL.Record({
    'id' : ImageId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'image' : ExternalBlob,
    'serviceTypeId' : ServiceTypeId,
  });
  const ServiceType = IDL.Record({
    'id' : ServiceTypeId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'bookingUrl' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : MessageId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'preferredService' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, ServiceTypeId, ExternalBlob],
        [PortfolioImage],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ServiceType], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryItem' : IDL.Func([ImageId], [IDL.Bool], []),
    'deleteService' : IDL.Func([ServiceTypeId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getGalleryItem' : IDL.Func(
        [ImageId],
        [IDL.Opt(PortfolioImage)],
        ['query'],
      ),
    'getService' : IDL.Func([ServiceTypeId], [IDL.Opt(ServiceType)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'listGalleryItems' : IDL.Func([], [IDL.Vec(PortfolioImage)], ['query']),
    'listGalleryItemsByService' : IDL.Func(
        [ServiceTypeId],
        [IDL.Vec(PortfolioImage)],
        ['query'],
      ),
    'listServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
    'setContactInfo' : IDL.Func([ContactInfo], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'updateService' : IDL.Func(
        [ServiceTypeId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };