/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export type Timestamp = bigint;
export interface ServiceType {
    id: ServiceTypeId;
    name: string;
    slug: string;
    description: string;
}
export interface PortfolioImage {
    id: ImageId;
    title: string;
    createdAt: Timestamp;
    image: ExternalBlob;
    serviceTypeId: ServiceTypeId;
}
export interface CreateBookingRequest {
    customerName: string;
    serviceType: string;
    customerPhone: string;
    notes?: string;
    requestedDate: string;
    requestedTime: string;
    techId: TechId;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type TechId = bigint;
export interface NailTech {
    id: TechId;
    name: string;
    town: string;
    address: string;
    specialties: Array<string>;
}
export interface BookingView {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    serviceType: string;
    customerPhone: string;
    cancellationReason?: string;
    createdAt: Timestamp;
    confirmedDate?: string;
    confirmedTime?: string;
    updatedAt: Timestamp;
    notes?: string;
    requestedDate: string;
    requestedTime: string;
    techId: TechId;
    adminNotes?: string;
    techName: string;
}
export type ImageId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ContactMessage {
    id: MessageId;
    name: string;
    createdAt: Timestamp;
    preferredService: string;
    email: string;
    message: string;
}
export type MessageId = bigint;
export type ServiceTypeId = bigint;
export interface RescheduleRequest {
    bookingId: BookingId;
    adminNotes?: string;
    newDate: string;
    newTime: string;
}
export interface ContactInfo {
    hours: string;
    email: string;
    address: string;
    phone: string;
    bookingUrl: string;
}
export enum BookingStatus {
    Rescheduled = "Rescheduled",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addGalleryItem(title: string, serviceTypeId: ServiceTypeId, image: ExternalBlob): Promise<PortfolioImage>;
    addService(name: string, description: string, slug: string): Promise<ServiceType>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: BookingId, reason: string | null): Promise<BookingView | null>;
    completeBooking(bookingId: BookingId, adminNotes: string | null): Promise<BookingView | null>;
    confirmBooking(bookingId: BookingId, adminNotes: string | null): Promise<BookingView | null>;
    deleteGalleryItem(id: ImageId): Promise<boolean>;
    deleteService(id: ServiceTypeId): Promise<boolean>;
    getBooking(bookingId: BookingId): Promise<BookingView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactInfo(): Promise<ContactInfo>;
    getGalleryItem(id: ImageId): Promise<PortfolioImage | null>;
    getNailTech(techId: TechId): Promise<NailTech | null>;
    getService(id: ServiceTypeId): Promise<ServiceType | null>;
    isCallerAdmin(): Promise<boolean>;
    listBookings(statusFilter: BookingStatus | null): Promise<Array<BookingView>>;
    listContacts(): Promise<Array<ContactMessage>>;
    listGalleryItems(): Promise<Array<PortfolioImage>>;
    listGalleryItemsByService(serviceTypeId: ServiceTypeId): Promise<Array<PortfolioImage>>;
    listNailTechs(): Promise<Array<NailTech>>;
    listServices(): Promise<Array<ServiceType>>;
    rescheduleBooking(req: RescheduleRequest): Promise<BookingView | null>;
    setContactInfo(info: ContactInfo): Promise<void>;
    submitBooking(req: CreateBookingRequest): Promise<BookingView>;
    submitContact(name: string, email: string, message: string, preferredService: string): Promise<ContactMessage>;
    updateService(id: ServiceTypeId, name: string, description: string, slug: string): Promise<boolean>;
}
import type { BookingId as _BookingId, BookingStatus as _BookingStatus, BookingView as _BookingView, CreateBookingRequest as _CreateBookingRequest, ExternalBlob as _ExternalBlob, ImageId as _ImageId, NailTech as _NailTech, PortfolioImage as _PortfolioImage, RescheduleRequest as _RescheduleRequest, ServiceType as _ServiceType, ServiceTypeId as _ServiceTypeId, TechId as _TechId, Timestamp as _Timestamp, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: ServiceTypeId, arg2: ExternalBlob): Promise<PortfolioImage> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PortfolioImage_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PortfolioImage_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addService(arg0: string, arg1: string, arg2: string): Promise<ServiceType> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: BookingId, arg1: string | null): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeBooking(arg0: BookingId, arg1: string | null): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmBooking(arg0: BookingId, arg1: string | null): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGalleryItem(arg0: ImageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceTypeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getBooking(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getGalleryItem(arg0: ImageId): Promise<PortfolioImage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItem(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItem(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNailTech(arg0: TechId): Promise<NailTech | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNailTech(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNailTech(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceTypeId): Promise<ServiceType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBookings(arg0: BookingStatus | null): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContacts(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts();
            return result;
        }
    }
    async listGalleryItems(): Promise<Array<PortfolioImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryItems();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryItems();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGalleryItemsByService(arg0: ServiceTypeId): Promise<Array<PortfolioImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryItemsByService(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryItemsByService(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNailTechs(): Promise<Array<NailTech>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNailTechs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNailTechs();
            return result;
        }
    }
    async listServices(): Promise<Array<ServiceType>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async rescheduleBooking(arg0: RescheduleRequest): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleBooking(to_candid_RescheduleRequest_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleBooking(to_candid_RescheduleRequest_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async setContactInfo(arg0: ContactInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactInfo(arg0);
            return result;
        }
    }
    async submitBooking(arg0: CreateBookingRequest): Promise<BookingView> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_CreateBookingRequest_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BookingView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_CreateBookingRequest_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BookingView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ContactMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateService(arg0: ServiceTypeId, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_BookingStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_BookingView_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingView): BookingView {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PortfolioImage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioImage): Promise<PortfolioImage> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingView]): BookingView | null {
    return value.length === 0 ? null : from_candid_BookingView_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioImage]): Promise<PortfolioImage | null> {
    return value.length === 0 ? null : await from_candid_PortfolioImage_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NailTech]): NailTech | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceType]): ServiceType | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ImageId;
    title: string;
    createdAt: _Timestamp;
    image: _ExternalBlob;
    serviceTypeId: _ServiceTypeId;
}): Promise<{
    id: ImageId;
    title: string;
    createdAt: Timestamp;
    image: ExternalBlob;
    serviceTypeId: ServiceTypeId;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image),
        serviceTypeId: value.serviceTypeId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerName: string;
    status: _BookingStatus;
    serviceType: string;
    customerPhone: string;
    cancellationReason: [] | [string];
    createdAt: _Timestamp;
    confirmedDate: [] | [string];
    confirmedTime: [] | [string];
    updatedAt: _Timestamp;
    notes: [] | [string];
    requestedDate: string;
    requestedTime: string;
    techId: _TechId;
    adminNotes: [] | [string];
    techName: string;
}): {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    serviceType: string;
    customerPhone: string;
    cancellationReason?: string;
    createdAt: Timestamp;
    confirmedDate?: string;
    confirmedTime?: string;
    updatedAt: Timestamp;
    notes?: string;
    requestedDate: string;
    requestedTime: string;
    techId: TechId;
    adminNotes?: string;
    techName: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n18(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        customerPhone: value.customerPhone,
        cancellationReason: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.cancellationReason)),
        createdAt: value.createdAt,
        confirmedDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.confirmedDate)),
        confirmedTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.confirmedTime)),
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.notes)),
        requestedDate: value.requestedDate,
        requestedTime: value.requestedTime,
        techId: value.techId,
        adminNotes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.adminNotes)),
        techName: value.techName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rescheduled: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): BookingStatus {
    return "Rescheduled" in value ? BookingStatus.Rescheduled : "Confirmed" in value ? BookingStatus.Confirmed : "Cancelled" in value ? BookingStatus.Cancelled : "Completed" in value ? BookingStatus.Completed : "Pending" in value ? BookingStatus.Pending : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingView>): Array<BookingView> {
    return value.map((x)=>from_candid_BookingView_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioImage>): Promise<Array<PortfolioImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PortfolioImage_n9(_uploadFile, _downloadFile, x)));
}
function to_candid_BookingStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBookingRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingRequest): _CreateBookingRequest {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RescheduleRequest_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RescheduleRequest): _RescheduleRequest {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus | null): [] | [_BookingStatus] {
    return value === null ? candid_none() : candid_some(to_candid_BookingStatus_n27(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingId: BookingId;
    adminNotes?: string;
    newDate: string;
    newTime: string;
}): {
    bookingId: _BookingId;
    adminNotes: [] | [string];
    newDate: string;
    newTime: string;
} {
    return {
        bookingId: value.bookingId,
        adminNotes: value.adminNotes ? candid_some(value.adminNotes) : candid_none(),
        newDate: value.newDate,
        newTime: value.newTime
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    serviceType: string;
    customerPhone: string;
    notes?: string;
    requestedDate: string;
    requestedTime: string;
    techId: TechId;
}): {
    customerName: string;
    serviceType: string;
    customerPhone: string;
    notes: [] | [string];
    requestedDate: string;
    requestedTime: string;
    techId: _TechId;
} {
    return {
        customerName: value.customerName,
        serviceType: value.serviceType,
        customerPhone: value.customerPhone,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        requestedDate: value.requestedDate,
        requestedTime: value.requestedTime,
        techId: value.techId
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    Rescheduled: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == BookingStatus.Rescheduled ? {
        Rescheduled: null
    } : value == BookingStatus.Confirmed ? {
        Confirmed: null
    } : value == BookingStatus.Cancelled ? {
        Cancelled: null
    } : value == BookingStatus.Completed ? {
        Completed: null
    } : value == BookingStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
